# Generated by Django 6.0.4 on 2026-04-27 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_interaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('after_rem_phase', 'After Rem Phase')], default='daily', max_length=20),
        ),
    ]
