# Generated by Django 6.0.4 on 2026-05-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_memory_memory_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_consolidated',
            field=models.BooleanField(default=False),
        ),
    ]
