# Generated by Django 6.0.4 on 2026-04-27 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_memory_memory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('daily', 'Daily'), ('rem_phase', 'REM Phase')], default='daily', max_length=20),
        ),
    ]
