# Generated by Django 6.0.4 on 2026-05-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_character_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trial_interactions_used',
            field=models.IntegerField(default=0),
        ),
    ]
